backend:
  name: github
  repo: tarasolyak/tarasolyak.github.io
  branch: main

media_folder: images/uploads

collections:
  - name: "projects"
    label: "Проєкти"
    files:
      - name: "projects"
        label: "Список проєктів"
        file: "_data/projects.json"
        fields:
          - name: "projects"
            label: "Проєкти"
            widget: "list"
            fields:
              - { label: "Назва", name: "title", widget: "string" }
              - { label: "Опис", name: "description", widget: "text" }
              - { label: "GitHub посилання", name: "github_url", widget: "string" }
              - { label: "Превью", name: "image", widget: "image", required: false }
